services:
  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: .docker/Dockerfile.govcms
    ports:
      - 0:80
    volumes:
      - /root/.composer
      - /var/www/html/sites
    develop:
      watch:
        - action: sync
          path: .
          target: /app/web/profiles/govcms
        - action: rebuild
          path: composer.json

  ##########################################
  # mariadb: The database used by local
  ##########################################
  mariadb:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    volumes:
      - /var/lib/mysql

networks:
  default:
    external: false
